const items = [
  { value: "United Kingdom", id: 1 },
  { value: "Australia", id: 2 },
  { value: "Germany", id: 3 },
  { value: "123 rock street", id: 4 },
  { value: "@@ Some street", id: 5 },
  { value: "Argentina", id: 6 },
  { value: "United States", id: 7, site: {} },
  { value: "Russia", id: 8 },
  { value: "United Kingdom", id: 1 },
  { value: "Australia", id: 2 },
  { value: "Germany", id: 3 },
  { value: "123 rock street", id: 4 },
  { value: "@@ Some street", id: 5 },
  { value: "Argentina", id: 6 },
  { value: "United States", id: 7 },
  { value: "Russia", id: 8 },
  { value: "United Kingdom", id: 1 },
  { value: "Australia", id: 2 },
  { value: "Germany", id: 3 },
  { value: "123 rock street", id: 4 },
  { value: "@@ Some street", id: 5 },
  { value: "Argentina", id: 6 },
  { value: "United States", id: 7 },
  { value: "Russia", id: 8 },
  { value: "United Kingdom", id: 1 },
  { value: "Australia", id: 2 },
  { value: "Germany", id: 3 },
  { value: "123 rock street", id: 4 },
  { value: "@@ Some street", id: 5 },
  { value: "Argentina", id: 6 },
  { value: "United States", id: 7 },
  { value: "Russia", id: 8 }
];

export default items;
